### ISSUE TITLE
Settings and Custom Shortcuts

### ISSUE THREAD

**Issue by kclapper** [kclapper/counter#8]
There should be a settings menu that lets people change their keyboard shortcuts:

Here are some thoughts:
- Should you only be able to change the keyboard shortcut on desktop?
- The customized shortcut should be persistent on desktop

**Comment by bmillzthedefector** [comment]
We should add a second set of keyboard shortcuts so that there are 2 simultaneous options that can both be user assigned to any key combo in the settings menu.

Would be great to be able to show/hide every element of the app from the settings menu. (info pane, clock, counter buttons, counter, etc)

It would be nice to resurrect the font size options within the settings menu.

**Comment by kclapper** [comment]
> We should add a second set of keyboard shortcuts so that there are 2 simultaneous options that can both be user assigned to any key combo in the settings menu.

I don't think I understand what you mean. So each setting/command can have two keyboard shortcuts? For instance `incrementCount` could be done with `Alt+Shift+Plus` or `Cmd+D`.

Or do you mean that any one shortcut could actuate multiple settings/commands, like increasing the count and font size at the same time?

**Comment by kclapper** [comment]
> Would be great to be able to show/hide every element of the app from the settings menu. (info pane, clock, counter buttons, counter, etc)

Shouldn't the take counter be permanent? What would be the rationale for hiding it?

**Comment by bmillzthedefector** [comment]
> > Shouldn't the take counter be permanent? What would be the rationale for hiding it?
>
There's a use case where you'd use the app to display the time of day (clock) only without counting takes

**Comment by kclapper** [comment]
Closed by commit 6a906338b218159268f404f084eda35711e7424e
